import localFont from "next/font/local";

import "./globals.css";

// Satoshi Font
const satoshi = localFont({
  src: [
    {
      path: "./fonts/Satoshi-Regular.woff",
      weight: "400", // Regular
    },
    {
      path: "./fonts/Satoshi-Medium.woff",
      weight: "500", // Medium
    },
    {
      path: "./fonts/Satoshi-Black.woff",
      weight: "900", // Black
    },
  ],
  variable: "--font-satoshi",
});

// Metadata
export const metadata = {
  title: "SuuaveFTX",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`font-satoshi`}>{children}</body>
    </html>
  );
}
